export {
  createSubjectRegistry,
  createDefaultSubjectFields,
  subjectRegistry,
  isSupportedSubject,
  normalizeProfileFields,
  buildCardPresentation,
  DIFFICULTIES,
  getSubjectProfile,
  getStudyPresentations,
  hasSubjectFields,
  normalizeDeckSubjectFields,
  normalizeEntrySubjectFields,
  normalizeSubject,
  resolveSubjectDirection,
  storedSubject,
  SUBJECT_IDS,
  SUBJECTS,
} from "./subjects.js";
