begin;

create table if not exists public.user_devices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  device_id uuid not null,
  device_name text,
  platform text,
  app_version text,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, device_id)
);

create index if not exists user_devices_user_id_idx
  on public.user_devices(user_id);

drop trigger if exists user_devices_touch_updated_at on public.user_devices;
create trigger user_devices_touch_updated_at
before update on public.user_devices
for each row execute procedure public.touch_updated_at();

create table if not exists public.user_library_decks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  sync_id uuid not null,
  deck_kind text not null default 'local'
    check (deck_kind in ('local', 'hub', 'account')),
  hub_deck_id uuid references public.hub_decks(id) on delete set null,
  title text not null,
  description text,
  source_language text not null,
  target_language text not null,
  tertiary_language text,
  tags text[] not null default '{}',
  words_count integer not null default 0,
  content_hash text,
  latest_version integer not null default 0,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, sync_id)
);

create index if not exists user_library_decks_user_id_idx
  on public.user_library_decks(user_id);

create index if not exists user_library_decks_sync_id_idx
  on public.user_library_decks(sync_id);

drop trigger if exists user_library_decks_touch_updated_at on public.user_library_decks;
create trigger user_library_decks_touch_updated_at
before update on public.user_library_decks
for each row execute procedure public.touch_updated_at();

create table if not exists public.user_library_deck_versions (
  id uuid primary key default gen_random_uuid(),
  library_deck_id uuid not null references public.user_library_decks(id) on delete cascade,
  version integer not null,
  file_path text not null,
  file_format text not null,
  file_size_bytes bigint not null,
  checksum_sha256 text,
  words_count integer not null default 0,
  created_at timestamptz not null default now(),
  unique (library_deck_id, version)
);

create index if not exists user_library_deck_versions_library_deck_id_idx
  on public.user_library_deck_versions(library_deck_id);

create index if not exists user_library_deck_versions_library_deck_id_version_idx
  on public.user_library_deck_versions(library_deck_id, version desc);

create table if not exists public.progress_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  op_id uuid not null,
  device_id uuid not null,
  device_seq bigint not null default 0,
  deck_sync_id uuid not null,
  word_external_id text not null,
  reviewed_at timestamptz not null,
  rating text not null,
  queue_type text not null,
  payload_json jsonb not null default '{}'::jsonb,
  server_seq bigint generated by default as identity,
  created_at timestamptz not null default now(),
  unique (user_id, op_id)
);

create index if not exists progress_events_user_id_server_seq_idx
  on public.progress_events(user_id, server_seq);

create index if not exists progress_events_user_id_deck_sync_id_idx
  on public.progress_events(user_id, deck_sync_id);

create index if not exists progress_events_user_id_reviewed_at_idx
  on public.progress_events(user_id, reviewed_at desc);

alter table public.user_devices enable row level security;
alter table public.user_library_decks enable row level security;
alter table public.user_library_deck_versions enable row level security;
alter table public.progress_events enable row level security;

drop policy if exists "user_devices_select_own" on public.user_devices;
drop policy if exists "user_devices_insert_own" on public.user_devices;
drop policy if exists "user_devices_update_own" on public.user_devices;
drop policy if exists "user_devices_delete_own" on public.user_devices;

create policy "user_devices_select_own"
on public.user_devices
for select
to authenticated
using (user_id = auth.uid());

create policy "user_devices_insert_own"
on public.user_devices
for insert
to authenticated
with check (user_id = auth.uid());

create policy "user_devices_update_own"
on public.user_devices
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "user_devices_delete_own"
on public.user_devices
for delete
to authenticated
using (user_id = auth.uid());

drop policy if exists "user_library_decks_select_own" on public.user_library_decks;
drop policy if exists "user_library_decks_insert_own" on public.user_library_decks;
drop policy if exists "user_library_decks_update_own" on public.user_library_decks;
drop policy if exists "user_library_decks_delete_own" on public.user_library_decks;

create policy "user_library_decks_select_own"
on public.user_library_decks
for select
to authenticated
using (user_id = auth.uid());

create policy "user_library_decks_insert_own"
on public.user_library_decks
for insert
to authenticated
with check (user_id = auth.uid());

create policy "user_library_decks_update_own"
on public.user_library_decks
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "user_library_decks_delete_own"
on public.user_library_decks
for delete
to authenticated
using (user_id = auth.uid());

drop policy if exists "user_library_deck_versions_select_own" on public.user_library_deck_versions;
drop policy if exists "user_library_deck_versions_insert_own" on public.user_library_deck_versions;
drop policy if exists "user_library_deck_versions_delete_own" on public.user_library_deck_versions;

create policy "user_library_deck_versions_select_own"
on public.user_library_deck_versions
for select
to authenticated
using (
  exists (
    select 1
    from public.user_library_decks d
    where d.id = library_deck_id
      and d.user_id = auth.uid()
  )
);

create policy "user_library_deck_versions_insert_own"
on public.user_library_deck_versions
for insert
to authenticated
with check (
  exists (
    select 1
    from public.user_library_decks d
    where d.id = library_deck_id
      and d.user_id = auth.uid()
  )
);

create policy "user_library_deck_versions_delete_own"
on public.user_library_deck_versions
for delete
to authenticated
using (
  exists (
    select 1
    from public.user_library_decks d
    where d.id = library_deck_id
      and d.user_id = auth.uid()
  )
);

drop policy if exists "progress_events_select_own" on public.progress_events;
drop policy if exists "progress_events_insert_own" on public.progress_events;
drop policy if exists "progress_events_update_own" on public.progress_events;
drop policy if exists "progress_events_delete_own" on public.progress_events;

create policy "progress_events_select_own"
on public.progress_events
for select
to authenticated
using (user_id = auth.uid());

create policy "progress_events_insert_own"
on public.progress_events
for insert
to authenticated
with check (user_id = auth.uid());

create policy "progress_events_update_own"
on public.progress_events
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "progress_events_delete_own"
on public.progress_events
for delete
to authenticated
using (user_id = auth.uid());

commit;
